[package]
name = "snack"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.7", package = "gtk4", features = [ "v4_18" ] }
tokio = { version = "1.46.0", features = ["full"] }
xmpp = "0.6.0"
log = "0.4.27"
env_logger = "0.11.8"

[build-dependencies]
glib-build-tools = "0.20.0"
